```{r setup, include = FALSE}

library('groundhog')
groundhog.library(
  c(
    'papaja',
    'reticulate',
    'tidyverse',
    'broom',
    'cowplot',
    'MESS', # for AUCs
    'lsr', # for effect sizes
    'pwr', # for power calculations
    'brms', # for mixed effects modeling
    'BayesFactor',# for Bayesian t test
    'jsonlite', #parsing data from sort_trial
    'afex' #for anova
  ), "2022-12-01"
)
r_refs("r-references.bib")

```

```{r load_and_format_data, echo=FALSE, cache=TRUE}
pilot.raw_df <- read_csv('../experiments/pilots/movingOccludersConfidence/data/jatos_resultfiles_batch1/all_data.csv') %>%
  filter(frame_index==0)%>%
  mutate(subj_id=subject_identifier,
         correct = as.numeric(correct),
         RT = as.numeric(RT),
         present=as.numeric(present),
         resp = response==presence_key,
         confidence=1-confidence) 

```

Excluding participants with too many errors

```{r exclude, echo=FALSE, cache=TRUE,include=FALSE}

pilot.acc = pilot.raw_df %>%
  filter(test_part %in% c('test1','test2'))%>%
  group_by(subj_id)%>%
  summarise(acc=mean(correct))

pilot.to_exclude = pilot.acc %>%
  filter(acc<=0.5) %>%
  pull(subj_id)

pilot.df <- pilot.raw_df %>%
  filter(test_part %in% c('test1','test2') &
           !(subj_id %in% pilot.to_exclude) &
           RT>100) 
  
```

Plotting accuracy

```{r figure1, echo=FALSE, cache=TRUE, warning=FALSE, include=FALSE}

pilot.acc_plot <- pilot.df %>%
  group_by(subj_id,hide_proportion,present) %>%
  summarise(acc=mean(correct)) %>%
  group_by(hide_proportion,present) %>%
  summarise(mean_acc=mean(acc),
            se_acc=se(acc)) %>%
  ggplot(aes(x=hide_proportion, y=mean_acc)) +
  geom_line(size=1) +
  facet_wrap(~present)+
  labs(x='array width', y='accuracy')
  
```

Plotting RT

```{r figure2, echo=FALSE, cache=TRUE,warning=FALSE}

pilot.RT_plot <- pilot.df %>%
  filter(correct==1)%>%
  mutate(present=factor(present, levels=c(0,1), labels=c('absent','present')))%>%
  group_by(subj_id,hide_proportion,present) %>%
  summarise(RT=median(RT)) %>%
  group_by(subj_id) %>%
  mutate(centered_RT = RT-mean(RT)) %>%
  group_by(hide_proportion,present) %>%
  summarise(mean_RT=mean(RT),
            se_RT=se(centered_RT)) %>%
  ggplot(aes(x=hide_proportion, y=mean_RT)) +
  geom_line(size=1) +
  geom_ribbon(aes(ymax=mean_RT+se_RT,ymin=mean_RT-se_RT),alpha=0.5)+
  facet_wrap(~present)+
  labs(x='array width', y='RT')+
  theme_bw()

pilot.RT_plot
```

Plotting confidence

```{r figure2, echo=FALSE, cache=TRUE,warning=FALSE}

pilot.confidence_plot <- pilot.df %>%
  # filter(correct==1)%>%
  mutate(present=factor(present, levels=c(0,1), labels=c('absent','present')))%>%
  group_by(subj_id,hide_proportion,present) %>%
  summarise(confidence=mean(confidence, na.rm=T)) %>%
  group_by(subj_id) %>%
  mutate(centered_confidence = confidence-mean(confidence)) %>%
  group_by(hide_proportion,present) %>%
  summarise(mean_confidence=mean(confidence),
            se_confidence=se(centered_confidence)) %>%
  ggplot(aes(x=hide_proportion, y=mean_confidence)) +
  geom_line(size=1) +
  geom_ribbon(aes(ymax=mean_confidence+se_confidence,ymin=mean_confidence-se_confidence),alpha=0.5)+
  facet_wrap(~present)+
  labs(x='array width', y='confidence')+
  theme_bw()

pilot.confidence_plot
```

Tests

```{r tests, echo=FALSE, cache=TRUE, inlcude=FALSE, warning=FALSE}

pilot.contrasts <- pilot.df %>%
  filter(correct==1)%>%
  group_by(subj_id,present) %>%
  summarise(
    occlusion_cost = median(RT[hide_proportion==0.25])-median(RT[hide_proportion==0.05])
    )

  
```

